/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminZonesRouteImport } from './routes/admin/zones'
import { Route as AdminVendorsRouteImport } from './routes/admin/vendors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPromosRouteImport } from './routes/admin/promos'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminMealsRouteImport } from './routes/admin/meals'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminFlashSalesRouteImport } from './routes/admin/flash-sales'
import { Route as AdminFinancialRouteImport } from './routes/admin/financial'
import { Route as AdminExpensesRouteImport } from './routes/admin/expenses'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminDealsRouteImport } from './routes/admin/deals'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminBundlesRouteImport } from './routes/admin/bundles'
import { Route as AdminBranchesRouteImport } from './routes/admin/branches'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/admin/promos',
  path: '/admin/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMealsRoute = AdminMealsRouteImport.update({
  id: '/admin/meals',
  path: '/admin/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/admin/kitchen',
  path: '/admin/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFlashSalesRoute = AdminFlashSalesRouteImport.update({
  id: '/admin/flash-sales',
  path: '/admin/flash-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/admin/financial',
  path: '/admin/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealsRoute = AdminDealsRouteImport.update({
  id: '/admin/deals',
  path: '/admin/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBundlesRoute = AdminBundlesRouteImport.update({
  id: '/admin/bundles',
  path: '/admin/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/bundles': typeof AdminBundlesRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/deals': typeof AdminDealsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/flash-sales': typeof AdminFlashSalesRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-account'
    | '/my-orders'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/branches'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/deals'
    | '/admin/drivers'
    | '/admin/expenses'
    | '/admin/financial'
    | '/admin/flash-sales'
    | '/admin/kitchen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/zones'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-account'
    | '/my-orders'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/branches'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/deals'
    | '/admin/drivers'
    | '/admin/expenses'
    | '/admin/financial'
    | '/admin/flash-sales'
    | '/admin/kitchen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/zones'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/my-account'
    | '/my-orders'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin/branches'
    | '/admin/bundles'
    | '/admin/campaigns'
    | '/admin/deals'
    | '/admin/drivers'
    | '/admin/expenses'
    | '/admin/financial'
    | '/admin/flash-sales'
    | '/admin/kitchen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/meals'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/revenue'
    | '/admin/rewards'
    | '/admin/sales'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/zones'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyAccountRoute: typeof MyAccountRoute
  MyOrdersRoute: typeof MyOrdersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminBundlesRoute: typeof AdminBundlesRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDealsRoute: typeof AdminDealsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminFlashSalesRoute: typeof AdminFlashSalesRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMealsRoute: typeof AdminMealsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/admin/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meals': {
      id: '/admin/meals'
      path: '/admin/meals'
      fullPath: '/admin/meals'
      preLoaderRoute: typeof AdminMealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/admin/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flash-sales': {
      id: '/admin/flash-sales'
      path: '/admin/flash-sales'
      fullPath: '/admin/flash-sales'
      preLoaderRoute: typeof AdminFlashSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/admin/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deals': {
      id: '/admin/deals'
      path: '/admin/deals'
      fullPath: '/admin/deals'
      preLoaderRoute: typeof AdminDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bundles': {
      id: '/admin/bundles'
      path: '/admin/bundles'
      fullPath: '/admin/bundles'
      preLoaderRoute: typeof AdminBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyAccountRoute: MyAccountRoute,
  MyOrdersRoute: MyOrdersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminBundlesRoute: AdminBundlesRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDealsRoute: AdminDealsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminFlashSalesRoute: AdminFlashSalesRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMealsRoute: AdminMealsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
